### PR TITLE
Issue #115: token_type is present in the body of resource owner password grant response.

### PR DESCRIPTION
**Pull request by vroldanbet**
- Added builder call to add token_type in OIDCController
- Removed default value from lombok pojo so it forces clients to add it manually

### CODE REVIEW

**Comment by vroldanbet** [comment]
@hjacobs could you please take a look at this?

**Comment by hjacobs** [comment]
@vroldanbet I see no test to verify that the bug actually exists (and that it gets fixed). Can you add one please?

**Comment by vroldanbet** [comment]
@hjacobs that's true, but by removing the default value in the lombok pojo, all tests previously passing test failed. Does that work for you?

**Comment by hjacobs** [comment]
@vroldanbet ok, but removing the default value is already a change, so can you verify with a test that the original version is broken and the current PR is not?

**Comment by vroldanbet** [comment]
@hjacobs sure thing!

**Comment by harti2006** [comment]
The thing is: The change in the pojo did actually break the tests (as expected) and the additional builder method call fixed everything again. The lessons learned in this case are:
- Never use pojos with default values when testing your API
- If default values are necessary in the production code, the test-pojos should be completely separate ones.

**Comment by vroldanbet** [comment]
@hjacobs @harti2006 added a test to demonstrate the issue, which fails with the original code where a default value was used for token_type. All other tests that are supposed to fail actually pass a result of binding responses to the lombok-based pojo. Jackson instantiates OIDCCreateTokenResponse via default constructor (as opposed to builder, as done in OIDCController.response()) and as a result the default value is set and all the tests silently pass.

**Comment by harti2006** [comment]
:+1:

**Pull request merged**
