### PR TITLE
fixes #105

### LINKED ISSUE #105: Implicit Flow callback URL parameters
Hi,

Using Implicit Flow, in the consent screen, these are the URLs the user gets redirected to if he clicks Allow/Deny:

http://localhost:8080/callback**?**access_token=JWT_TOKEN&token_type=Bearer&expires_in=28800&scope=uid&state=

http://localhost:8080/callback**?**error=access_denied&state=

This URL comes from the server in the Location header.

There is an issue with this URL, because the OAuth2 Spec indicates that they should be passed as fragments (https://tools.ietf.org/html/rfc6749#section-4.2.2) and not query parameters, i.e.:

http://localhost:8080/callback**#**access_token=JWT_TOKEN&token_type=Bearer&expires_in=28800&scope=uid&state=

http://localhost:8080/callback**#**error=access_denied&state=

### PR DESCRIPTION
**Pull request by matosf**
changed reponse url from query to fragment parameters

### CODE REVIEW

**Comment by hjacobs** [comment]
This hopefully breaks the tests (as you haven't changed any test)..

**Comment by matosf** [comment]
@hjacobs 
ran mvn test instead of verify... :(
will fix soon.

**Comment by matosf** [comment]
@hjacobs now is fixed :)

**Comment by hjacobs** [comment]
:+1:

**Comment by harti2006** [comment]
This Pull Request breaks the Authorization Code Grant Flow, because in this case, the parameters should go into the query part of the url, not into the fragment part.

Unfortunately, we had not test case for this at merge-time, but I added one in another branch and just saw it failing after pulling the current master in: https://github.com/zalando/planb-provider/commit/e4c196250742060e8fe057045d045ee6648c7e88

**Comment by vroldanbet** [comment]
@harti2006 you are right, the fragment-based callback should only happen on the implicit flow (when the access_token is returned) and not in the authorization code flow grant.

**Comment by matosf** [comment]
Correct, fragments are only for Implict Grant.

Authorization Code Grant
https://tools.ietf.org/html/rfc6749#section-4.1.2

Implicit Grant
https://tools.ietf.org/html/rfc6749#section-4.2.2

This breaks because of the change to noConsentedScopesResponse?

**Comment by harti2006** [comment]
@matosf exactly. Therefore, only the "access denied" case is broken.

**Comment by matosf** [comment]
Are you fixing it on your PR, or should I in a new one?
Em 13/04/2016 5:02 da tarde, "André Hartmann" <notifications@github.com>
escreveu:

**Comment by harti2006** [comment]
@matosf yes, I provided the fix, as well as the unit test, that spotted the bug, in PR #110

**Comment by matosf** [comment]
Thanks!
Em 14/04/2016 9:37 da manhã, "André Hartmann" <notifications@github.com>
escreveu:

**Pull request merged**
