### PR TITLE
upgrade openjdk

### PR DESCRIPTION
**Pull request by vroldanbet**
upgrade openjdk

### CODE REVIEW

**Comment by midumitrescu** [comment]
:+1:

**Comment by vroldanbet** [comment]
:+1:

**Comment by vroldanbet** [comment]
:+1:

**Comment by hjacobs** [comment]
You can use `:latest`.

**Comment by vroldanbet** [comment]
@hjacobs done

**Comment by hjacobs** [comment]
:+1:

**Comment by vroldanbet** [comment]
:+1:

**Pull request merged**
